# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group.sg-0838ad2e105c5c736:
resource "aws_security_group" "sg-0838ad2e105c5c736" {
  description = "ecsworkshop-base/MeshGW-Proxy-Fargate-Service/Service/SecurityGroup"
  tags        = {}
  tags_all    = {}
  vpc_id      = aws_vpc.vpc-057a64aaa8d96235b.id
}
