# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-0bccbdd46fe42086d__rtbassoc-0f434f60d94db19fc:
resource "aws_route_table_association" "subnet-0bccbdd46fe42086d__rtbassoc-0f434f60d94db19fc" {
  route_table_id = aws_route_table.rtb-07a8574f5a56a964b.id
  subnet_id      = aws_subnet.subnet-0bccbdd46fe42086d.id
}
