# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-0a5216ba6c4a20153__rtbassoc-038efba10ddfe850b:
resource "aws_route_table_association" "subnet-0a5216ba6c4a20153__rtbassoc-038efba10ddfe850b" {
  route_table_id = aws_route_table.rtb-0d8f7e3bfefba66ec.id
  subnet_id      = aws_subnet.subnet-0a5216ba6c4a20153.id
}
