# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_appmesh_virtual_router.ecs-mesh__FrontEnd:
resource "aws_appmesh_virtual_router" "ecs-mesh__FrontEnd" {
  mesh_name = aws_appmesh_mesh.ecs-mesh.id
  name      = "FrontEnd"
  tags      = {}
  tags_all  = {}

  spec {
    listener {
      port_mapping {
        port     = 3000
        protocol = "http"
      }
    }
  }
}
