# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_appmesh_virtual_service.ecs-mesh__ecsdemo-frontend_service_local:
resource "aws_appmesh_virtual_service" "ecs-mesh__ecsdemo-frontend_service_local" {
  mesh_name = aws_appmesh_mesh.ecs-mesh.id
  name      = "ecsdemo-frontend.service.local"
  tags      = {}
  tags_all  = {}

  spec {
    provider {

      virtual_router {
        virtual_router_name = aws_appmesh_virtual_router.ecs-mesh__FrontEnd.name
      }
    }
  }
}
