# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-090ea4dad86354a04__rtbassoc-0ac2dc785830afd6b:
resource "aws_route_table_association" "subnet-090ea4dad86354a04__rtbassoc-0ac2dc785830afd6b" {
  route_table_id = aws_route_table.rtb-0351413b64f81ca90.id
  subnet_id      = aws_subnet.subnet-090ea4dad86354a04.id
}
