# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ecs_service.container-demo__ecsdemo-crystal:
resource "aws_ecs_service" "container-demo__ecsdemo-crystal" {
  cluster                            = aws_ecs_cluster.container-demo.arn
  deployment_maximum_percent         = 200
  deployment_minimum_healthy_percent = 50
  desired_count                      = 1
  enable_ecs_managed_tags            = false
  enable_execute_command             = false
  health_check_grace_period_seconds  = 0
  launch_type                        = "FARGATE"
  name                               = "ecsdemo-crystal"
  platform_version                   = "LATEST"
  scheduling_strategy                = "REPLICA"
  tags                               = {}
  tags_all                           = {}
  task_definition                    = aws_ecs_task_definition.ecsworkshopcrystalTaskDefAEA199B7_6.arn
  triggers                           = {}

  deployment_circuit_breaker {
    enable   = false
    rollback = false
  }

  deployment_controller {
    type = "ECS"
  }

  network_configuration {
    assign_public_ip = false
    security_groups = [
      aws_security_group.sg-0f7e3ec5d7c01ab3b.id,
    ]
    subnets = [
      aws_subnet.subnet-0a5216ba6c4a20153.id,
      aws_subnet.subnet-0b7ccfbce3d25d6ad.id,
      aws_subnet.subnet-0bccbdd46fe42086d.id,
    ]
  }

  service_registries {
    container_port = 0
    port           = 0
    registry_arn   = aws_service_discovery_service.srv-eykbseyd34u6qggn.arn
  }
}
