# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_appautoscaling_policy.ecs__service_container-demo_ecsdemo-crystal__ecs_service_DesiredCount__ecsworkshopcrystalCrystalFargateServiceTaskCountTargetCPUAutoscaling641C41A1:
resource "aws_appautoscaling_policy" "ecs__service_container-demo_ecsdemo-crystal__ecs_service_DesiredCount__ecsworkshopcrystalCrystalFargateServiceTaskCountTargetCPUAutoscaling641C41A1" {
  name               = "ecsworkshopcrystalCrystalFargateServiceTaskCountTargetCPUAutoscaling641C41A1"
  policy_type        = "TargetTrackingScaling"
  resource_id        = "service/container-demo/ecsdemo-crystal"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"

  target_tracking_scaling_policy_configuration {
    disable_scale_in   = false
    scale_in_cooldown  = 30
    scale_out_cooldown = 30
    target_value       = 20

    predefined_metric_specification {
      predefined_metric_type = "ECSServiceAverageCPUUtilization"
    }
  }
}
