# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_cloudwatch_log_group.ecsworkshop-frontend:
resource "aws_cloudwatch_log_group" "ecsworkshop-frontend" {
  name              = "ecsworkshop-frontend"
  retention_in_days = 7
  tags              = {}
  tags_all          = {}
}
