# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.r-ecsworkshop-base-InstanceSSMCBFA3CF0-N0K8YHX2VEUM:
resource "aws_iam_role" "r-ecsworkshop-base-InstanceSSMCBFA3CF0-N0K8YHX2VEUM" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "ec2.amazonaws.com"
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  force_detach_policies = false
  managed_policy_arns = [
    "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM",
  ]
  max_session_duration = 3600
  name                 = "ecsworkshop-base-InstanceSSMCBFA3CF0-N0K8YHX2VEUM"
  path                 = "/"
  tags                 = {}
  tags_all             = {}
}
