# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_appautoscaling_policy.ecs__service_container-demo_ecsdemo-frontend__ecs_service_DesiredCount__ecsworkshopfrontendFrontEndFargateServiceTaskCountTargetCPUAutoscalingD024FEBE:
resource "aws_appautoscaling_policy" "ecs__service_container-demo_ecsdemo-frontend__ecs_service_DesiredCount__ecsworkshopfrontendFrontEndFargateServiceTaskCountTargetCPUAutoscalingD024FEBE" {
  name               = "ecsworkshopfrontendFrontEndFargateServiceTaskCountTargetCPUAutoscalingD024FEBE"
  policy_type        = "TargetTrackingScaling"
  resource_id        = "service/container-demo/ecsdemo-frontend"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"

  target_tracking_scaling_policy_configuration {
    disable_scale_in   = false
    scale_in_cooldown  = 30
    scale_out_cooldown = 30
    target_value       = 50

    predefined_metric_specification {
      predefined_metric_type = "ECSServiceAverageCPUUtilization"
    }
  }
}
