# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# ../../scripts/052-get-iam-attached-role-policies.sh
# aws_iam_role_policy_attachment.r-ecsworkshop-frontend-FrontEndTaskDefExecutionRole3-11S67VJCT4IOG__CloudWatchLogsFullAccess:
resource "aws_iam_role_policy_attachment" "r-ecsworkshop-frontend-FrontEndTaskDefExecutionRole3-11S67VJCT4IOG__CloudWatchLogsFullAccess" {
  policy_arn = "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
  role       = aws_iam_role.r-ecsworkshop-frontend-FrontEndTaskDefExecutionRole3-11S67VJCT4IOG.id
}
