# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.r-ecsworkshop-base-meshgwproxytaskdefTaskRoleBD296B1-NJZEXY41X498:
resource "aws_iam_role" "r-ecsworkshop-base-meshgwproxytaskdefTaskRoleBD296B1-NJZEXY41X498" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "ecs-tasks.amazonaws.com"
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  force_detach_policies = false
  managed_policy_arns = [
    "arn:aws:iam::aws:policy/AWSAppMeshEnvoyAccess",
    "arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess",
    "arn:aws:iam::aws:policy/CloudWatchFullAccess",
  ]
  max_session_duration = 3600
  name                 = "ecsworkshop-base-meshgwproxytaskdefTaskRoleBD296B1-NJZEXY41X498"
  path                 = "/"
  tags                 = {}
  tags_all             = {}
}
