# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group.sg-06eef3d0bbb93d60e:
resource "aws_security_group" "sg-06eef3d0bbb93d60e" {
  description = "ecsworkshop-frontend/FrontEndFargateService/SecurityGroup"
  tags        = {}
  tags_all    = {}
  vpc_id      = aws_vpc.vpc-057a64aaa8d96235b.id
}
