# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_nat_gateway.nat-0c0ea9aebd6258d7e:
resource "aws_nat_gateway" "nat-0c0ea9aebd6258d7e" {
  allocation_id     = aws_eip.eipalloc-0dc2f504e4713dcc9.id
  connectivity_type = "public"
  subnet_id         = aws_subnet.subnet-00a09562a158644f8.id
  tags = {
    "Name" = "ecsworkshop-base/BaseVPC/PublicSubnet3"
  }
  tags_all = {
    "Name" = "ecsworkshop-base/BaseVPC/PublicSubnet3"
  }
}
