# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ecs_cluster.container-demo:
resource "aws_ecs_cluster" "container-demo" {
  name     = "container-demo"
  tags     = {}
  tags_all = {}

  setting {
    name  = "containerInsights"
    value = "enabled"
  }
}
