# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy.r-ecsworkshop-frontend-FrontEndTaskDefExecutionRole3-11S67VJCT4IOG__FrontEndTaskDefExecutionRoleDefaultPolicyD4E08F77:
resource "aws_iam_role_policy" "r-ecsworkshop-frontend-FrontEndTaskDefExecutionRole3-11S67VJCT4IOG__FrontEndTaskDefExecutionRoleDefaultPolicyD4E08F77" {
  name = "FrontEndTaskDefExecutionRoleDefaultPolicyD4E08F77"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "logs:CreateLogStream",
            "logs:PutLogEvents",
          ]
          Effect   = "Allow"
          Resource = format("arn:aws:logs:%s:%s:log-group:ecsworkshop-frontend:*", data.aws_region.current.name, data.aws_caller_identity.current.account_id)
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.r-ecsworkshop-frontend-FrontEndTaskDefExecutionRole3-11S67VJCT4IOG.id
}
