# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table.rtb-067ca9457ae19f31d:
resource "aws_route_table" "rtb-067ca9457ae19f31d" {
  propagating_vgws = []
  route = [
    {
      carrier_gateway_id         = ""
      cidr_block                 = "0.0.0.0/0"
      core_network_arn           = ""
      destination_prefix_list_id = ""
      egress_only_gateway_id     = ""
      gateway_id                 = ""
      instance_id                = null
      ipv6_cidr_block            = null
      local_gateway_id           = ""
      nat_gateway_id             = aws_nat_gateway.nat-036c508568ce804fc.id
      network_interface_id       = ""
      transit_gateway_id         = ""
      vpc_endpoint_id            = ""
      vpc_peering_connection_id  = ""
    },
  ]
  tags = {
    "Name" = "Private RouteTable 2- squid-ecr"
  }
  tags_all = {
    "Name" = "Private RouteTable 2- squid-ecr"
  }
  vpc_id = aws_vpc.vpc-090fcf5a7a3b94d20.id
}
