# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy.r-squid-ecr-CodeBuildServiceRole-13V9IEE48IOCX__CC:
resource "aws_iam_role_policy" "r-squid-ecr-CodeBuildServiceRole-13V9IEE48IOCX__CC" {
  name = "CC"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "codecommit:GitPull",
          ]
          Effect = "Allow"
          Resource = [
            format("arn:aws:codecommit:%s:%s:squid-proxy", data.aws_region.current.name, data.aws_caller_identity.current.account_id),
          ]
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.r-squid-ecr-CodeBuildServiceRole-13V9IEE48IOCX.id
}
