# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_flow_log.fl-0612bbc6bea876ca7:
resource "aws_flow_log" "fl-0612bbc6bea876ca7" {
  iam_role_arn         = format("arn:aws:iam::%s:role/squid-ecr-VPCFlowLogRoleRole-W155I2A4B2OL", data.aws_caller_identity.current.account_id)
  log_destination_type = "cloud-watch-logs"
  lifecycle {
    ignore_changes = [log_format]
  }
  log_destination=aws_cloudwatch_log_group.squid-flowlogs.arn
  #log_format               = "&{version} &{account-id} &{interface-id} &{srcaddr} &{dstaddr} &{srcport} &{dstport} &{protocol} &{packets} &{bytes} &{start} &{end} &{action} &{log-status}"
  max_aggregation_interval = 600
  tags                     = {}
  tags_all                 = {}
  traffic_type             = "ALL"
  vpc_id                   = aws_vpc.vpc-090fcf5a7a3b94d20.id
}
