# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy.r-squid-ecr-CodeBuildServiceRole-13V9IEE48IOCX__ECRAuth:
resource "aws_iam_role_policy" "r-squid-ecr-CodeBuildServiceRole-13V9IEE48IOCX__ECRAuth" {
  name = "ECRAuth"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "ecr:GetAuthorizationToken",
          ]
          Effect   = "Allow"
          Resource = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.r-squid-ecr-CodeBuildServiceRole-13V9IEE48IOCX.id
}
