# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.r-squid-ecr-CodeCommitChangeEventRole-1P8MCPP7TNO11:
resource "aws_iam_role" "r-squid-ecr-CodeCommitChangeEventRole-1P8MCPP7TNO11" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "events.amazonaws.com"
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  force_detach_policies = false
  managed_policy_arns   = []
  max_session_duration  = 3600
  name                  = "squid-ecr-CodeCommitChangeEventRole-1P8MCPP7TNO11"
  path                  = "/"
  tags                  = {}
  tags_all              = {}

  inline_policy {
    name = "cwe-pipeline-execution"
    policy = jsonencode(
      {
        Statement = [
          {
            Action   = "codepipeline:StartPipelineExecution"
            Effect   = "Allow"
            Resource = aws_codepipeline.r-squid-ecr-SquidProxy-CodeCommitEvents-pipeline.arn
          },
        ]
        Version = "2012-10-17"
      }
    )
  }
}
