# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpc_endpoint_service.vpce-svc-09041d05a3a2059cc:
resource "aws_vpc_endpoint_service" "vpce-svc-09041d05a3a2059cc" {
  acceptance_required = false
  allowed_principals  = []
  network_load_balancer_arns = [
    aws_lb.arn_aws_elasticloadbalancing_net_squid.arn,
  ]
  supported_ip_address_types = [
    "ipv4",
  ]
  tags     = {}
  tags_all = {}
}
