# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_nat_gateway.nat-036c508568ce804fc:
resource "aws_nat_gateway" "nat-036c508568ce804fc" {
  allocation_id     = aws_eip.eipalloc-0acc910452c2d2ec4.id
  connectivity_type = "public"
  subnet_id         = aws_subnet.subnet-00f1f3e65a0dfabf6.id
  tags = {
    "Name" = "Public NATGateway 2 - squid-ecr"
  }
  tags_all = {
    "Name" = "Public NATGateway 2 - squid-ecr"
  }
}
