# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_s3_bucket.b_squid-ecr-codepipelineartifactstorebucket-3qgzkmb8mf0k:
resource "aws_s3_bucket" "b_squid-ecr-codepipelineartifactstorebucket-3qgzkmb8mf0k" {
  bucket              = "squid-ecr-codepipelineartifactstorebucket-3qgzkmb8mf0k"
  object_lock_enabled = false
  tags                = {}
  tags_all            = {}




}
