# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ecs_cluster.squid-ecr-ECSCluster:
resource "aws_ecs_cluster" "squid-ecr-ECSCluster" {
  name     = "squid-ecr-ECSCluster"
  tags     = {}
  tags_all = {}

  setting {
    name  = "containerInsights"
    value = "enabled"
  }
}
