# File generated by aws2tf see https://github.com/aws-samples/aws2tf
resource "aws_cloudwatch_log_group" "squid-ecr-ECSTaskLogGroup-s2EMEBzWf9GA" {
  name              = "squid-ecr-ECSTaskLogGroup-s2EMEBzWf9GA"
  retention_in_days = 5
  tags              = {}
  tags_all          = {}
}

resource "aws_cloudwatch_log_group" "squid-flowlogs" {
  name              = "squid-flowlogs"
  retention_in_days = 5
  tags              = {}
  tags_all          = {}
}
