# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_nat_gateway.nat-0ec7a73a5b7000d2d:
resource "aws_nat_gateway" "nat-0ec7a73a5b7000d2d" {
  allocation_id     = aws_eip.eipalloc-031062066ecd1a324.id
  connectivity_type = "public"
  subnet_id         = aws_subnet.subnet-06a1663084c09f60b.id
  tags = {
    "Name" = "Public NATGateway 1 - squid-ecr"
  }
  tags_all = {
    "Name" = "Public NATGateway 1 - squid-ecr"
  }
}
