# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-00f1f3e65a0dfabf6__rtbassoc-07f3127e28c5a6de5:
resource "aws_route_table_association" "subnet-00f1f3e65a0dfabf6__rtbassoc-07f3127e28c5a6de5" {
  route_table_id = aws_route_table.rtb-04df3b5a592773c27.id
  subnet_id      = aws_subnet.subnet-00f1f3e65a0dfabf6.id
}
