# File generated by aws2tf see https://github.com/aws-samples/aws2tf
resource "aws_lb" "arn_aws_elasticloadbalancing_net_squid" {
  enable_cross_zone_load_balancing = false
  enable_deletion_protection       = false
  internal                         = true
  ip_address_type                  = "ipv4"
  load_balancer_type               = "network"
  name                             = "squid-e-NLB-1FYF3MKVQICGH"
  security_groups                  = []
  subnets = [
    aws_subnet.subnet-0445458c15388c163.id,
    aws_subnet.subnet-08aae867856e9c1ac.id,
  ]
  tags     = {}
  tags_all = {}

  access_logs {
    bucket  = "squid-ecr-accesslogss3-1hqy0o9c4mhch"
    enabled = false
    prefix  = "nlb"
  }

}
