# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-06a1663084c09f60b__rtbassoc-0b1e4cbf05fb6cbae:
resource "aws_route_table_association" "subnet-06a1663084c09f60b__rtbassoc-0b1e4cbf05fb6cbae" {
  route_table_id = aws_route_table.rtb-04df3b5a592773c27.id
  subnet_id      = aws_subnet.subnet-06a1663084c09f60b.id
}
