# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_codecommit_repository.squid-proxy:
resource "aws_codecommit_repository" "squid-proxy" {
  repository_name = "squid-proxy"
  tags            = {}
  tags_all        = {}
}
