# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_internet_gateway.igw-06bb834c9146068a8:
resource "aws_internet_gateway" "igw-06bb834c9146068a8" {
  tags = {
    "Name" = "IGW - squid-ecr"
  }
  tags_all = {
    "Name" = "IGW - squid-ecr"
  }
  vpc_id = aws_vpc.vpc-090fcf5a7a3b94d20.id
}
