# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-08aae867856e9c1ac__rtbassoc-0df7dec1a7a9afbcd:
resource "aws_route_table_association" "subnet-08aae867856e9c1ac__rtbassoc-0df7dec1a7a9afbcd" {
  route_table_id = aws_route_table.rtb-00c2a3920ce34d43f.id
  subnet_id      = aws_subnet.subnet-08aae867856e9c1ac.id
}
