# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# ../../scripts/052-get-iam-attached-role-policies.sh
# aws_iam_role_policy_attachment.r-ecsworkshop-crystal-TaskDefTaskRole1EDB4A67-B60AY8893QDS__CloudWatchFullAccess:
resource "aws_iam_role_policy_attachment" "r-ecsworkshop-crystal-TaskDefTaskRole1EDB4A67-B60AY8893QDS__CloudWatchFullAccess" {
  policy_arn = "arn:aws:iam::aws:policy/CloudWatchFullAccess"
  role       = aws_iam_role.r-ecsworkshop-crystal-TaskDefTaskRole1EDB4A67-B60AY8893QDS.id
}
