# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_appmesh_route.ecs-mesh__FrontEnd__MeshFrontEndVRRoute:
resource "aws_appmesh_route" "ecs-mesh__FrontEnd__MeshFrontEndVRRoute" {
  mesh_name           = aws_appmesh_mesh.ecs-mesh.id
  name                = "MeshFrontEndVRRoute"
  tags                = {}
  tags_all            = {}
  virtual_router_name = aws_appmesh_virtual_router.ecs-mesh__FrontEnd.name

  spec {
    priority = 0

    http_route {
      action {
        weighted_target {
          virtual_node = aws_appmesh_virtual_node.ecs-mesh__frontend.name
          weight       = 1
        }
      }

      match {
        prefix = "/"
      }
    }
  }
}
