# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_subnet.subnet-0bccbdd46fe42086d:
resource "aws_subnet" "subnet-0bccbdd46fe42086d" {
  assign_ipv6_address_on_creation                = false
  availability_zone                              = "eu-west-1a"
  cidr_block                                     = "10.1.0.96/27"
  enable_dns64                                   = false
  enable_resource_name_dns_a_record_on_launch    = false
  enable_resource_name_dns_aaaa_record_on_launch = false
  ipv6_native                                    = false
  map_public_ip_on_launch                        = false
  private_dns_hostname_type_on_launch            = "ip-name"
  tags = {
    "Name"                = "ecsworkshop-base/BaseVPC/PrivateSubnet1"
    "aws-cdk:subnet-name" = "Private"
    "aws-cdk:subnet-type" = "Private"
  }
  tags_all = {
    "Name"                = "ecsworkshop-base/BaseVPC/PrivateSubnet1"
    "aws-cdk:subnet-name" = "Private"
    "aws-cdk:subnet-type" = "Private"
  }
  vpc_id = aws_vpc.vpc-057a64aaa8d96235b.id
}
