# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# ../../scripts/052-get-iam-attached-role-policies.sh
# aws_iam_role_policy_attachment.r-ecsworkshop-base-meshgwproxytaskdefTaskRoleBD296B1-NJZEXY41X498__CloudWatchFullAccess:
resource "aws_iam_role_policy_attachment" "r-ecsworkshop-base-meshgwproxytaskdefTaskRoleBD296B1-NJZEXY41X498__CloudWatchFullAccess" {
  policy_arn = "arn:aws:iam::aws:policy/CloudWatchFullAccess"
  role       = aws_iam_role.r-ecsworkshop-base-meshgwproxytaskdefTaskRoleBD296B1-NJZEXY41X498.id
}
