# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_cloudwatch_log_group.ecsworkshop-nodejs-ecsworkshopNodejsF670245F-RUPl52tiHWdZ:
resource "aws_cloudwatch_log_group" "ecsworkshop-nodejs-ecsworkshopNodejsF670245F-RUPl52tiHWdZ" {
  name              = "ecsworkshop-nodejs-ecsworkshopNodejsF670245F-RUPl52tiHWdZ"
  retention_in_days = 7
  tags              = {}
  tags_all          = {}
}
