# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_instance.i-026e347bca6a4f00f:
resource "aws_instance" "i-026e347bca6a4f00f" {
  ami                                  = "ami-09102fbce920ce7cb"
  associate_public_ip_address          = false
  availability_zone                    = "eu-west-1a"
  disable_api_stop                     = false
  disable_api_termination              = false
  ebs_optimized                        = false
  get_password_data                    = false
  hibernation                          = false
  iam_instance_profile                 = aws_iam_instance_profile.ecsworkshop-base-InstanceInstanceProfileAB5AEF02-0C7zyILrZhf5.id
  instance_initiated_shutdown_behavior = "stop"
  instance_type                        = "t3.medium"
  monitoring                           = false
  placement_partition_number           = 0
  secondary_private_ips                = []
  security_groups                      = []
  source_dest_check                    = true
  subnet_id                            = aws_subnet.subnet-0bccbdd46fe42086d.id
  tags = {
    "Name"        = "ecsworkshop-base-stresstool"
    "Patch Group" = "AccountGuardian-PatchGroup-DO-NOT-DELETE"
  }
  tags_all = {
    "Name"        = "ecsworkshop-base-stresstool"
    "Patch Group" = "AccountGuardian-PatchGroup-DO-NOT-DELETE"
  }
  tenancy = "default"
  lifecycle {
    ignore_changes = [user_data_replace_on_change, associate_public_ip_address, user_data, user_data_base64]
  }
  user_data_base64 = filebase64sha256("i-026e347bca6a4f00f.sh")
  vpc_security_group_ids = [
    aws_security_group.sg-0f7e3ec5d7c01ab3b.id,
  ]

  capacity_reservation_specification {
    capacity_reservation_preference = "open"
  }

  cpu_options {
    core_count       = 1
    threads_per_core = 2
  }

  credit_specification {
    cpu_credits = "unlimited"
  }

  enclave_options {
    enabled = false
  }

  maintenance_options {
    auto_recovery = "default"
  }

  metadata_options {
    http_endpoint               = "enabled"
    http_put_response_hop_limit = 1
    http_tokens                 = "optional"
    instance_metadata_tags      = "disabled"
  }

  private_dns_name_options {
    enable_resource_name_dns_a_record    = false
    enable_resource_name_dns_aaaa_record = false
    hostname_type                        = "ip-name"
  }

  root_block_device {
    delete_on_termination = true
    encrypted             = false
    tags                  = {}
    throughput            = 0
    volume_size           = 8
    volume_type           = "gp2"
  }
  user_data_replace_on_change = false
}
