# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_appmesh_gateway_route.ecs-mesh__ecsworkshop-vgw__frontend-router:
resource "aws_appmesh_gateway_route" "ecs-mesh__ecsworkshop-vgw__frontend-router" {
  mesh_name            = aws_appmesh_mesh.ecs-mesh.id
  name                 = "frontend-router"
  tags                 = {}
  tags_all             = {}
  virtual_gateway_name = aws_appmesh_virtual_gateway.ecs-mesh__ecsworkshop-vgw.name

  spec {
    priority = 0

    http_route {
      action {

        target {

          virtual_service {
            virtual_service_name = aws_appmesh_virtual_service.ecs-mesh__ecsdemo-frontend_service_local.name
          }
        }
      }

      match {
        prefix = "/"
      }
    }
  }
}
