# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lb.arn_aws_elasticloadbalancing_eu-west-2_566972129213_loadbalancer_net_ecswo-MeshG-FLLW6SVH5ZXC_931d0198707acc37:
resource "aws_lb" "arn_aws_elasticloadbalancing_eu-west-2_566972129213_loadbalancer_net_ecswo-MeshG-FLLW6SVH5ZXC_931d0198707acc37" {
  enable_cross_zone_load_balancing = false
  enable_deletion_protection       = false
  internal                         = false
  ip_address_type                  = "ipv4"
  load_balancer_type               = "network"
  name                             = "ecswo-MeshG-FLLW6SVH5ZXC"
  security_groups                  = []
  subnets = [
    aws_subnet.subnet-00a09562a158644f8.id,
    aws_subnet.subnet-090ea4dad86354a04.id,
    aws_subnet.subnet-0a449930323b84bbf.id,
  ]
  tags     = {}
  tags_all = {}

  access_logs {
    bucket  = ""
    enabled = false
  }


}
