# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_nat_gateway.nat-0be8fc24ddb85402d:
resource "aws_nat_gateway" "nat-0be8fc24ddb85402d" {
  allocation_id     = aws_eip.eipalloc-09d44506d4717b45d.id
  connectivity_type = "public"
  subnet_id         = aws_subnet.subnet-0a449930323b84bbf.id
  tags = {
    "Name" = "ecsworkshop-base/BaseVPC/PublicSubnet1"
  }
  tags_all = {
    "Name" = "ecsworkshop-base/BaseVPC/PublicSubnet1"
  }
}
