# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy.r-ecsworkshop-base-meshgwproxytaskdefExecutionRoleC1-6EFVJAQ6X4TG__meshgwproxytaskdefExecutionRoleDefaultPolicyF5FABCAE:
resource "aws_iam_role_policy" "r-ecsworkshop-base-meshgwproxytaskdefExecutionRoleC1-6EFVJAQ6X4TG__meshgwproxytaskdefExecutionRoleDefaultPolicyF5FABCAE" {
  name = "meshgwproxytaskdefExecutionRoleDefaultPolicyF5FABCAE"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "logs:CreateLogStream",
            "logs:PutLogEvents",
          ]
          Effect   = "Allow"
          Resource = format("arn:aws:logs:%s:%s:log-group:ecsworkshop-mesh-gateway:*", data.aws_region.current.name, data.aws_caller_identity.current.account_id)
        },
        {
          Action   = "ec2:DescribeSubnets"
          Effect   = "Allow"
          Resource = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.r-ecsworkshop-base-meshgwproxytaskdefExecutionRoleC1-6EFVJAQ6X4TG.id
}
