# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group.sg-0f7e3ec5d7c01ab3b:
resource "aws_security_group" "sg-0f7e3ec5d7c01ab3b" {
  description = "Security group for frontend service to talk to backend services"
  tags        = {}
  tags_all    = {}
  vpc_id      = aws_vpc.vpc-057a64aaa8d96235b.id
}
