# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-00a09562a158644f8__rtbassoc-0ac2f433e55609a34:
resource "aws_route_table_association" "subnet-00a09562a158644f8__rtbassoc-0ac2f433e55609a34" {
  route_table_id = aws_route_table.rtb-040b26abbf7d9d50f.id
  subnet_id      = aws_subnet.subnet-00a09562a158644f8.id
}
