# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_internet_gateway.igw-0259dc3652d1731a8:
resource "aws_internet_gateway" "igw-0259dc3652d1731a8" {
  tags = {
    "Name" = "ecsworkshop-base/BaseVPC"
  }
  tags_all = {
    "Name" = "ecsworkshop-base/BaseVPC"
  }
  vpc_id = aws_vpc.vpc-057a64aaa8d96235b.id
}
