# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy.r-ecsworkshop-frontend-FrontEndTaskDefTaskRoleA1ABFC-B992OT8C1M49__FrontEndTaskDefTaskRoleDefaultPolicyF5EFB956:
resource "aws_iam_role_policy" "r-ecsworkshop-frontend-FrontEndTaskDefTaskRoleA1ABFC-B992OT8C1M49__FrontEndTaskDefTaskRoleDefaultPolicyF5EFB956" {
  name = "FrontEndTaskDefTaskRoleDefaultPolicyF5EFB956"
  policy = jsonencode(
    {
      Statement = [
        {
          Action   = "ec2:DescribeSubnets"
          Effect   = "Allow"
          Resource = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.r-ecsworkshop-frontend-FrontEndTaskDefTaskRoleA1ABFC-B992OT8C1M49.id
}
