# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lb_listener.arn_aws_elasticloadbalancing_eu-west-1_566972129213_listener_net_ecswo-MeshG-FLLW6SVH5ZXC_931d0198707acc37_9db189ec3902ca54:
resource "aws_lb_listener" "arn_aws_elasticloadbalancing_eu-west-1_566972129213_listener_net_ecswo-MeshG-FLLW6SVH5ZXC_931d0198707acc37_9db189ec3902ca54" {
  load_balancer_arn = aws_lb.arn_aws_elasticloadbalancing_eu-west-1_566972129213_loadbalancer_net_ecswo-MeshG-FLLW6SVH5ZXC_931d0198707acc37.arn
  port              = 80
  protocol          = "TCP"
  tags              = {}
  tags_all          = {}

  default_action {
    target_group_arn = aws_lb_target_group.arn_aws_elasticloadbalancing_eu-west-1_566972129213_targetgroup_ecswor-MeshG-MJA2UCVRN7TB_b9c93bfa2c16729f.arn
    type             = "forward"
  }
}
