# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_appmesh_virtual_service.ecs-mesh__ecsdemo-nodejs_service_local:
resource "aws_appmesh_virtual_service" "ecs-mesh__ecsdemo-nodejs_service_local" {
  mesh_name = aws_appmesh_mesh.ecs-mesh.id
  name      = "ecsdemo-nodejs.service.local"
  tags      = {}
  tags_all  = {}

  spec {
    provider {
      virtual_node {
        virtual_node_name = aws_appmesh_virtual_node.ecs-mesh__nodejs.name
      }
    }
  }
}
