# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_service_discovery_service.srv-hzimv2g2c4s3g2hv:
resource "aws_service_discovery_service" "srv-hzimv2g2c4s3g2hv" {
  name         = "ecsdemo-nodejs"
  namespace_id = aws_service_discovery_private_dns_namespace.ns-edlae6eydoee5gbk.id
  tags         = {}
  tags_all     = {}

  dns_config {
    namespace_id   = aws_service_discovery_private_dns_namespace.ns-edlae6eydoee5gbk.id
    routing_policy = "MULTIVALUE"

    dns_records {
      ttl  = 60
      type = "A"
    }
  }

  health_check_custom_config {
    failure_threshold = 1
  }
}
