# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_appmesh_virtual_node.ecs-mesh__crystal:
resource "aws_appmesh_virtual_node" "ecs-mesh__crystal" {
  mesh_name = aws_appmesh_mesh.ecs-mesh.id
  name      = "crystal"
  tags      = {}
  tags_all  = {}

  spec {

    listener {

      port_mapping {
        port     = 3000
        protocol = "http"
      }
    }

    logging {
      access_log {
        file {
          path = "/dev/stdout"
        }
      }
    }

    service_discovery {
      aws_cloud_map {
        attributes     = {}
        namespace_name = "service.local"
        service_name   = "ecsdemo-crystal"
      }
    }
  }
}
