# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lb_target_group.arn_aws_elasticloadbalancing_eu-west-1_566972129213_targetgroup_ecswor-MeshG-MJA2UCVRN7TB_b9c93bfa2c16729f:
resource "aws_lb_target_group" "arn_aws_elasticloadbalancing_eu-west-1_566972129213_targetgroup_ecswor-MeshG-MJA2UCVRN7TB_b9c93bfa2c16729f" {
  connection_termination            = false
  deregistration_delay              = "300"
  ip_address_type                   = "ipv4"
  load_balancing_cross_zone_enabled = "use_load_balancer_configuration"
  name                              = "ecswor-MeshG-MJA2UCVRN7TB"
  port                              = 80
  preserve_client_ip                = "false"
  protocol                          = "TCP"
  proxy_protocol_v2                 = false
  tags                              = {}
  tags_all                          = {}
  target_type                       = "ip"
  vpc_id                            = aws_vpc.vpc-057a64aaa8d96235b.id

  health_check {
    enabled             = true
    healthy_threshold   = 5
    interval            = 30
    port                = "traffic-port"
    protocol            = "TCP"
    timeout             = 10
    unhealthy_threshold = 2
  }

  stickiness {
    cookie_duration = 0
    enabled         = false
    type            = "source_ip"
  }

}
