# File generated by aws2tf see https://github.com/aws-samples/aws2tf
resource "aws_lb_listener" "app" {
  load_balancer_arn = data.aws_ssm_parameter.squid-lbarn.arn
  port              = 8080
  protocol          = "TCP"
  tags              = {}
  tags_all          = {}

  default_action {
    target_group_arn = aws_lb_target_group.app.arn
    type             = "forward"
  }
}
