# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_s3_bucket.b_squid-ecr-codepipelineartifactstorebucket-3qgzkmb8mf0k:
resource "aws_s3_bucket" "b_squid-ecr-codepipelineartifactstorebucket-3qgzkmb8mf0k" {
  #bucket              = "squid-ecr-codepipelineartifactstorebucket-3qgzkmb8mf0k"
  bucket              = format("squid-ecr-codepipeartifact-%s-%s",data.aws_caller_identity.current.account_id, data.aws_region.current.name)

  object_lock_enabled = false
  tags                = {}
  tags_all            = {}

  force_destroy       = true
}
