# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_cloudwatch_event_target.default__squid-ecr-CodeCommitChangeEventRule-1GAJZHZAR2R5E__squid-ecr-CodeCommitEventsRule:
resource "aws_cloudwatch_event_target" "default__squid-ecr-CodeCommitChangeEventRule-1GAJZHZAR2R5E__squid-ecr-CodeCommitEventsRule" {
  arn            = aws_codepipeline.r-squid-ecr-SquidProxy-CodeCommitEvents-pipeline.arn
  event_bus_name = "default"
  lifecycle {
    ignore_changes = [input_transformer[0].input_template]
  }
  role_arn  = aws_iam_role.r-squid-ecr-CodeCommitChangeEventRole-1P8MCPP7TNO11.arn
  rule      = "squid-ecr-CodeCommitChangeEventRule-1GAJZHZAR2R5E"
  target_id = "squid-ecr-CodeCommitEventsRule"
}
