# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy.r-squid-ecr-CodeBuildServiceRole-13V9IEE48IOCX__CB:
resource "aws_iam_role_policy" "r-squid-ecr-CodeBuildServiceRole-13V9IEE48IOCX__CB" {
  name = "CB"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "codebuild:CreateReportGroup",
            "codebuild:CreateReport",
            "Codebuild:UpdateReport",
            "codebuild:BatchPutTestCases",
            "codebuild:BatchPutCodeCoverages",
          ]
          Effect = "Allow"
          Resource = [
            format("arn:aws:codebuild:%s:%s:report-group/squid-ecr-SquidProxyBuild-*", data.aws_region.current.name, data.aws_caller_identity.current.account_id),
          ]
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.r-squid-ecr-CodeBuildServiceRole-13V9IEE48IOCX.id
}
