# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.r-squid-ecr-VPCFlowLogRoleRole-W155I2A4B2OL:
resource "aws_iam_role" "r-squid-ecr-VPCFlowLogRoleRole-W155I2A4B2OL" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "vpc-flow-logs.amazonaws.com"
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  force_detach_policies = false
  managed_policy_arns   = []
  max_session_duration  = 3600
  name                  = "squid-ecr-VPCFlowLogRoleRole-W155I2A4B2OL"
  path                  = "/"
  tags                  = {}
  tags_all              = {}

  inline_policy {
    name = "CW"
    policy = jsonencode(
      {
        Statement = [
          {
            Action = [
              "logs:CreateLogGroup",
              "logs:CreateLogStream",
              "logs:PutLogEvents",
            ]
            Effect   = "Allow"
            Resource = format("arn:aws:logs:%s:%s:log-group:squid-ecr-VPCFlowLogGroup-86KjvUjzYCwZ:*", data.aws_region.current.name, data.aws_caller_identity.current.account_id)
          },
        ]
        Version = "2012-10-17"
      }
    )
  }
}
