# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-0445458c15388c163__rtbassoc-0e8a86d783bbbf848:
resource "aws_route_table_association" "subnet-0445458c15388c163__rtbassoc-0e8a86d783bbbf848" {
  route_table_id = aws_route_table.rtb-067ca9457ae19f31d.id
  subnet_id      = aws_subnet.subnet-0445458c15388c163.id
}
