# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_s3_bucket.b_squid-ecr-accesslogss3-1hqy0o9c4mhch:
resource "aws_s3_bucket" "b_squid-ecr-accesslogss3-1hqy0o9c4mhch" {
  bucket              = format("squid-ecr-accesslogss3-%s-%s",data.aws_caller_identity.current.account_id, data.aws_region.current.name")
  object_lock_enabled = false
  tags                = {}
  tags_all            = {}
  force_destroy       = true



}
