# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# ../../scripts/052-get-iam-attached-role-policies.sh
# aws_iam_role_policy_attachment.r-squid-ecr-ECSTaskExecutionRole-BSNU23J2XF0S__AmazonECSTaskExecutionRolePolicy:
resource "aws_iam_role_policy_attachment" "r-squid-ecr-ECSTaskExecutionRole-BSNU23J2XF0S__AmazonECSTaskExecutionRolePolicy" {
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
  role       = aws_iam_role.r-squid-ecr-ECSTaskExecutionRole-BSNU23J2XF0S.id
}
