# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ecr_repository.squid-ecr-ecrrepository:
resource "aws_ecr_repository" "squid-ecr-ecrrepository" {
  image_tag_mutability = "MUTABLE"
  name                 = "squid-ecr-ecrrepository"
  tags                 = {}
  tags_all             = {}
  force_delete = true

  encryption_configuration {
    encryption_type = "AES256"
  }

  image_scanning_configuration {
    scan_on_push = true
  }
}
