# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy.r-squid-ecr-CodeBuildServiceRole-13V9IEE48IOCX__CW:
resource "aws_iam_role_policy" "r-squid-ecr-CodeBuildServiceRole-13V9IEE48IOCX__CW" {
  name = "CW"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "logs:CreateLogGroup",
            "logs:CreateLogStream",
            "logs:PutLogEvents",
          ]
          Effect   = "Allow"
          Resource = format("arn:aws:logs:%s:%s:log-group:/aws/codebuild/squid-ecr-*", data.aws_region.current.name, data.aws_caller_identity.current.account_id)
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.r-squid-ecr-CodeBuildServiceRole-13V9IEE48IOCX.id
}
